services:
  - type: web
    name: skygemaix
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: XAI_API_KEY
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false 