services:
  - type: web
    name: skygemaix
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: XAI_API_KEY
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: CLAUDE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GROK_API_KEY
        sync: false
      - key: FIREBASE_API_KEY
        sync: false
      - key: FIREBASE_AUTH_DOMAIN
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
      - key: FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: FIREBASE_APP_ID
        sync: false
      - key: FIREBASE_CREDS_JSON
        sync: false
      - key: FIREBASE_DB_URL
        sync: false
      - key: GENIKIT_URL
        sync: false
      - key: PYTHON_VERSION
        sync: false 